# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: A1 Labs
description: Enterprise Gen-AI
baseurl: ""
url: ""

#theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

google_analytics: G-TKZ7L5GZ7E

